### ISSUE TITLE
Plugin installation fails (v1.0.2)

### ISSUE THREAD

**Issue by BrandonMurugan** [scitedotai/scite-zotero-plugin#10]
When attempting to add scite-zotero-plugin (v1.0.2) to Zotero (v5.0.93) installation fails with the following error:
**The add-on "%S" could not be installed. It may be incompatible with this version of Zotero.**

This behaviour appears to be absent when attempting to install scite-zotero-plugin v1.0.1, and installation works as expected.

--
OS: Windows 10 Pro, Version	10.0.18362 Build 18362
Zotero: 5.0.93

**Comment by domenicrosati** [comment]
Hey @BrandonMurugan thanks for raising this to our attention.

We just tried to reproduce on Windows 10, Zotero: 5.0.93 with v1.0.2 and it worked.

We will continue to look out for the issue and ensure we test future releases against Windows 10 (if perhaps that is the issue)

**Comment by u-ashish** [comment]
Hi @BrandonMurugan , sorry to hear you ran into an issue. Could you do me a favor and confirm the file size of your `v1.0.2` download? Wondering if it might have been corrupted...

**Comment by BrandonMurugan** [comment]
Hi @u-ashish,ah good catch. The plugin download was corrupted. Re-downloaded and tried again and it works just fine.
Apologies for the false alarm! (Should have tried this before posting)

**Comment by u-ashish** [comment]
@BrandonMurugan Excellent, hope you find it useful. If you find any other issues or have feedback, feel free to let us know!
