### ISSUE TITLE
Cannot resize columns added by plugin 

### ISSUE THREAD

**Issue by danieltomasz** [scitedotai/scite-zotero-plugin#12]
I don't know if this is Zotero problem or plugin but I cannot manually resize columns that were added by the extension (Scite adding
3 additional columns : "supporting", 'mentioning', 'disputing' into main window)
Resizing Zotero window change the width of those columns, but resizing is impossible manually which sometimes make the content of these columns unreadable

Zotero 5.0.93, MacOS Big Sur 11.0.1, scite Plugin for Zotero 1.0.3

I posted on Zotero forum, one of the developers pointed me to you
https://forums.zotero.org/discussion/86193/cannot-resize-columns-added-by-plugin-scite-plugin#latest

**Comment by u-ashish** [comment]
Hi @danieltomasz

Thanks for reporting this. I know that normal Zotero columns are resizable, so presumably it is possible. I can take a look this week and I'll get back to you when I have a more concrete update.

**Comment by danieltomasz** [comment]
Thanks! To pinpoint more - The problem is when hovering columns from Scite plugin the specific handle "-||-" doesnt appear. That handle  is  used  to resize other column.

Another issue -  column "disputing" and  "Supporting" when  Zotero is resized are crammed too much when the total number of citation have more than  enough space
<img width="136" alt="image" src="https://user-images.githubusercontent.com/7980381/99318233-9f0b6a00-2867-11eb-8370-4bd0fa6a3118.png">

**Comment by u-ashish** [comment]
Hey there @danieltomasz 

I pushed an update this morning which should enable resizing, can you give it a try?

Zotero should auto-update, but if it doesn't, you can update in one of two ways:
- In Zotero, go to `Tools` -> `Add-ons` -> Right click the `scite Plugin for Zotero` and click `Find updates`. It should prompt you to restart.
- If somehow that doesn't work (let me know), you can manually download it from our releases page here: `https://github.com/scitedotai/scite-zotero-plugin/releases/tag/v1.0.5`

As for the problem of column sizes when you resize Zotero, I can take a look at that later, but let me know if manually resizing columns works and if that lets you sidestep the other resize issue.

**Comment by danieltomasz** [comment]
Yes, manually resizing  works now! Also problem of column size seems gone.  I am closing this issue, if there will be a problems with resizing I will reopen it.
