### ISSUE TITLE
Look into zotero v6 support

### ISSUE THREAD

**Issue by u-ashish** [scitedotai/scite-zotero-plugin#25]
```
Zotero is releasing new v5 betas in readiness for v 6. I am currently using 5.0.97-beta.36+9738d2055 and the scite extension no longer updates the cites. I checked the Firefox scite browser add-in and it is still working with the latest Firefox update 90.0.2 (64-bit).
```

Reported by a user -- look into it to see what I need to do to prepare our plugin for v6 support, backwards compatibility, etc.

![image](https://user-images.githubusercontent.com/14264791/129586155-7edd6557-85c8-4b4b-af8a-e9b7d7d1b13b.png)

**Comment by u-ashish** [comment]
Jack updated:

```
I just updated Zotero to 5.0.97-beta.37+ddc7be75c and the Scite plugin is once again fully functional. This is true on Mac and PC.

Thank you.
```

**Comment by jrennstich** [comment]
Unfortunately, the plugins do not load under Zotero 5.0.97-beta.40+952663de7
Apparently, others have faced issues here as well: https://forums.zotero.org/discussion/91449/add-ons-broken-in-the-latest-beta-version-bbt-zutilo-etc
@retorquere has found a fix, see thread https://github.com/retorquere/zotero-better-bibtex/issues/1899

**Comment by retorquere** [comment]
The conversation I had with the Zotero devs about this change can be found at https://github.com/retorquere/zotero-better-bibtex/discussions/1904.

**Comment by u-ashish** [comment]
Fixed, thanks for reporting and for the discussions 🙏
