### ISSUE TITLE
Scite plugin causing Zotero breakage in 5.0.96.3

### ISSUE THREAD

**Issue by dstillman** [scitedotai/scite-zotero-plugin#29]
https://forums.zotero.org/discussion/91584/zotero-app-not-working
https://forums.zotero.org/discussion/91576/report-id-1742130648

Both with 1.10.0

**Comment by u-ashish** [comment]
Weird, looking now, thanks for reporting it @dstillman

**Comment by u-ashish** [comment]
I reached out to them to see if they could try and send me their prefs.js file since the first person said everything worked after deleting it (trying to look at mine to see if anything could cause a weird interaction...)

**Comment by u-ashish** [comment]
Ahh, think I see it..

**Comment by RaulMendes94** [comment]
This bug also appeared to me.
I did a video showing how this happened: https://youtu.be/F6z53YXhyB8

**Comment by u-ashish** [comment]
Hi @RaulMendes94 thanks for the video -- so it looks like it happened after sorting. Could you confirm both your Zotero build version, and your scite plugin version?

**Comment by u-ashish** [comment]
Actually @RaulMendes94 I was able to replicate this on plugin `1.10.0` with Zotero `5.0.96.3`.

But if I use our plugin `1.11.1` (linked above), it doesn't happen -- can you try that plugin version and let me know if it works for you as well?

**Comment by RaulMendes94** [comment]
Thanks  u-ashish.
I deleted the extension and installed this new one (v1.11.1). Now it is working.

The Zotero version is 5.0.96.3.
The problem appeared today morning (almost 10 hours ago), so I think that the plugin version was the recent one updated automatically. But it worked after I deleted it and installed again.

**Comment by u-ashish** [comment]
awesome, thanks so much for confirming @RaulMendes94. I'll update it in the zotero discussion as well so people know to upgrade.

**Comment by RaulMendes94** [comment]
I think that it is important to remove it first before install this new version, because I failed when I tried to install it the first time just by dropping the new one without removing the old one.

It worked fine after I click the "remove" button and install the new one.

**Comment by u-ashish** [comment]
@RaulMendes94 

Yeah so if you are installing it directly, you need to do that. Alternatively, if you already have an old version installed, you can upgrade it directly to the latest by doing the following:

- Click Tools -> Add-Ons
- For the scite-zotero-plugin, click `More`
- Click `Check for updates`
- It should find the latest update and then prompt you to upgrade

(It also checks periodically but you can force the upgrade by doing this)
