### ISSUE TITLE
Time out error messages

### ISSUE THREAD

**Issue by champagnealexandre** [scitedotai/scite-zotero-plugin#30]
Hi,

Is this plugin still supposed to work? I only get timeouts in Zotero.

Thanks,

**Comment by jmnicholson** [comment]
Hi @champagnealexandre. Yes, this should still work. A few questions to help with debugging:

- Which version of Zotero are you using? 
- Which plugin version are you using?

Can you try to restart it and see if that resolves it? @u-ashish is out this week but will be able to help debug this further when he returns next week if you can let us know some more information.

**Comment by champagnealexandre** [comment]
I think the scite servers were actually causing this, it seems to work correctly today 🤷‍♂️

**Comment by u-ashish** [comment]
Thanks for confirming @champagnealexandre -- in general that shouldn't happen and everything should work but I'll investigate any sporadic API issues on our end.

Feel free to let us know if you run into any other problems in the future!

**Comment by champagnealexandre** [comment]
No problem, thanks!
