### ISSUE TITLE
Scite plugin does not work with short DOIs

### ISSUE THREAD

**Issue by Rhydderch** [scitedotai/scite-zotero-plugin#32]
Hi,

I activated the option to replace long format DOI by short ones.
Sadly, it seems Scite does not find the papers based on the short DOI (I tested this by creating a dashboard and entering short DOIs).

Here's a short DOI for example: 10/gdchd9

I realized this is only a problem in the web app; it's not related to the scite plugin.

**Comment by Rhydderch** [comment]
I realized this is only a problem in the web app; it's not related to the scite plugin.

**Comment by u-ashish** [comment]
Hi @Rhydderch yeah that's right, the main website doesn't convert short to long, although the plugin itself _should_ be converting them to long before requesting information from us (https://github.com/scitedotai/scite-zotero-plugin/blob/master/content/scite.ts#L40)

Were you not seeing tallies for short dois within zotero with the plugin?

**Comment by Rhydderch** [comment]
I think it was just a temporary glitch - perhaps due to my pc. So now it works perfectly :)
