### ISSUE TITLE
pull DOI from Extra field?

### ISSUE THREAD

**Issue by u-ashish** [scitedotai/scite-zotero-plugin#33]
https://forums.zotero.org/discussion/8014/no-doi-field-for-books/p2

Someone wanted to use DOI from the extra field for books where they provide it explicitly, I thought we did this but if not, should be easy enough...

**Comment by welpdx** [comment]
> I thought we did this

Yes you guys did in [Line 35](https://github.com/scitedotai/scite-zotero-plugin/blob/93e1d55eeca265309be2e5d78a0dd9ad9bf01bf8/content/scite.ts#L35). And it works for books with doi. 
Maybe the guy in that discussion didn't add "DOI:" in the Extras?

Anyways, I think this issue should be closed.

**Comment by u-ashish** [comment]
> > I thought we did this
> 
> Yes you guys did in [Line 35](https://github.com/scitedotai/scite-zotero-plugin/blob/93e1d55eeca265309be2e5d78a0dd9ad9bf01bf8/content/scite.ts#L35). And it works for books with doi. Maybe the guy in that discussion didn't add "DOI:" in the Extras?
> 
> Anyways, I think this issue should be closed.

Hiya -- yep. I saw we did too just forgot I made this issue! Thanks for reminding me :)

**Comment by welpdx** [comment]
@u-ashish  :D 
Also, good work on this plugin by the way!

**Comment by johnghill** [comment]
@u-ashish @welpdx Not sure if you prefer a new issue for this, but in my testing of `DOI:10.xxx` located in the `Extra` field of `Item Type=books`, scite's citation columns are populated correctly, but right-clicking `View scite report` returns "No DOI".

Plugin Version: 1.11.6
Zotero Version: 6.0.26
