### ISSUE TITLE
Suggestion: remove icon from Supporting/Disputing/Mentioning column entries

### ISSUE THREAD

**Issue by JessRiedel** [scitedotai/scite-zotero-plugin#43]
I have a lot of columns visible in my Library view.  I think it's unnecessary for the Supporting/Disputing/Mentioning entries to have an icon (green check, blue question mark, gray slash) in *each and every* entry (right?) since it doesn't provide new information.  

I presume the idea here is to make it visually easier to interpret the numbers, but if so can I suggest adding the icon to the column *header* rather than each entry?  This would actually be great, because then if I reside the columns to be as narrow the data typically is (1-4 digit number) it will still be easy to understand the header even though it won't be wide enough to fit "Supporting", "Disputing", or "Mentioning".

**Comment by u-ashish** [comment]
<img width="447" alt="Screen Shot 2022-04-06 at 1 25 38 PM" src="https://user-images.githubusercontent.com/14264791/162043491-be1b3247-f547-470e-a864-3e108ae548a0.png">

<img width="1138" alt="Screen Shot 2022-04-06 at 1 24 25 PM" src="https://user-images.githubusercontent.com/14264791/162043493-05e63241-398d-4706-842c-d3baddc338ed.png">

@JessRiedel Thanks for opening the issue; does this look better for you?

**Comment by JessRiedel** [comment]
Yes, much better! That was exactly what I had in mind.

**Comment by u-ashish** [comment]
@JessRiedel Great -- if you upgrade the plugin (or re-install via https://github.com/scitedotai/scite-zotero-plugin/releases/tag/v1.11.6) it should work. Let me know if it plays nice with your Zotero & any other plugins you have installed and if so, I'll close out the issue :).

**Comment by JessRiedel** [comment]
Looks great!

The only minor thing is that the "Total smart citations" has no icon but
does appear to have a blank space where the icon would go. So if I make
that column as narrow as the data there is just a blank space in the
heading of the column.  (In contrast, if I make one of the default columns
(like "Title") as narrow as possible, there is always at least the first
character (e.g., "T") visible.  (Supporting, Disputing, Mentioning, and
Total Distinct Citing Publications all have icons and behave correctly.)

The only other add-on I have for Zotero is Better BibTeX.  Haven't noticed
any issues yet; I will re-open this ticket if I do.

Thank you for the lightning fast implementation of this improvement!

**Comment by u-ashish** [comment]
@JessRiedel Sweet. We were actually discussing whether "Total smart citations" is worth keeping -- do you find it useful? I was concerned it might be confusing to have that and "Total citing publications" (1 publication can have more than 1 smart citation, so those counts will vary). I think it's hidden by default, but if it's something you find yourself looking for, I'll try and find a good icon for it

**Comment by JessRiedel** [comment]
Oh and the fix on the justification issue described in #44 also looks great.

**Comment by JessRiedel** [comment]
> We were actually discussing whether "Total smart citations" is worth keeping -- do you find it useful?

I only recently installed the add-on, so I can't say for sure whether I'll find it useful, but my inclination is that I won't.  In principle the info will be accessible even if you remove that column, since it's just the sum of supporting, contrasting, and mentioning (right?), and I can't actually think of many practical cases where I would want to know how many smart citations there are.  (I guess higher smart citation numbers could indicate more substantive discussion about a paper, rather than just an appearance of a single perfunctory cite in the introduction of the papers citing it? Hard to say.)

**Comment by JessRiedel** [comment]
I only recently installed the add-on, so I can't say for sure whether I'll
find it useful, but my inclination is that I won't.  In principle the info
will be accessible even if you remove that column, since it's just the sum
of supporting, contrasting, and mentioning (right?), and I can't actually
think of many practical cases where I would want to know how many smart
citations there are.  (I guess higher smart citation numbers could indicate
more substantive discussion about a paper, rather than just an appearance
of a single perfunctory cite in the introduction of the papers citing it?
Hard to say.)
