### ISSUE TITLE
Entries in Total smart citation column are improperly justified

### ISSUE THREAD

**Issue by JessRiedel** [scitedotai/scite-zotero-plugin#44]
The numbers in the Total smart citation column seem to have a large amount of white space on the left hand side of the column.  (Compare with, e.g., the "year" column or this add-on's "supporting" column.)  This is undesirable because if I try to resize the column to make it as wide as the widest number that appears in it (~5 digits), it starts cutting off the number while still leaving a bunch of white space on the left side.

**Comment by u-ashish** [comment]
Yep, just noticed this while I was looking at the other one. Will get a fix soon!
