### ISSUE TITLE
Register custom sort fields

### ISSUE THREAD

**Issue by dstillman** [scitedotai/scite-zotero-plugin#48]
I suspect this will affect this plugin:

https://groups.google.com/g/zotero-dev/c/kc0-C6-SA74/m/c_6ddjqIAAAJ

**Comment by dstillman** [comment]
Sorry — we decided to address this another way, so no change required. See the follow-up in that thread.

**Comment by u-ashish** [comment]
Thanks for following up @dstillman, will keep an eye out on that thread.
