### ISSUE TITLE
Scite doesn't work

### ISSUE THREAD

**Issue by Miaoyifei-mz** [scitedotai/scite-zotero-plugin#49]
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/60280844/183275265-559af7de-7c6f-455e-9c60-637b692f71a5.png">

## Version information

- zotero：6.0.11
- scite：1.11.6
- Mac OS：12.5

I restarted Zotero and reinstalled Scite, but it didn't work. I don't know if this is a bug or not.

**Comment by mildwall** [comment]
I have the same issue starting from today or yesterday. Is it a server-related problem?
- zotero：6.0.10
- scite：1.11.6
- Windows：10

**Comment by u-ashish** [comment]
Hey @mildwall and @Miaoyifei-mz  -- thanks for reporting this. I can take a look; I don't think it's a server side problem because our main website uses the same API and everything seems to work there (as does the API when I try it directly). Give me a day to get back to you, little tied down this evening, sorry about that!

**Comment by Miaoyifei-mz** [comment]
Thank you ! @u-ashish

**Comment by Miaoyifei-mz** [comment]
Hello, I suddenly noticed that Scite was working again.

**Comment by u-ashish** [comment]
@Miaoyifei-mz I actually can reproduce the bug you saw, working on a fix now. Weird that it works for you intermittently, though.

**Comment by mildwall** [comment]
@u-ashish Thank you for your effort. However, it still does not work on my computer.

**Comment by u-ashish** [comment]
Yeah, it's from an infrastructure change we made last week, sorry about this. Should be fixed today, will update you once it is!

**Comment by u-ashish** [comment]
as a mini update @mildwall and @Miaoyifei-mz -- we've identified the issue; it's happening intermittently but we're working on a fix.

Between now and then we're going to manually fix it periodically to prevent it from happening, so you should be able to use it for the most part.

I will update you as soon as I can once the full fix is ready (hopefully by tomorrow).

Sorry again if this interfered with your work!

**Comment by u-ashish** [comment]
@mildwall and @Miaoyifei-mz -- this should be fixed now. I'll keep the issue open for a couple days in case either of you notice anything else, but it should be all set from our end.

**Comment by u-ashish** [comment]
Should be fixed now, please feel free to re-open if it happens again. Thanks for letting me know to begin with!
