### ISSUE TITLE
Zotero 7.0.0 Installation fail

### ISSUE THREAD

**Issue by fishgirl7** [scitedotai/scite-zotero-plugin#57]
Hi All. Just upgraded to Zotero 7.0.0 beta to fix a bibliography issue (didn't work) and this has blown away my scite plugin which I live by.  
<img width="442" alt="zotero plugin fail" src="https://github.com/scitedotai/scite-zotero-plugin/assets/50823633/371afda7-ebc0-47d1-8f36-0ac1db51adbe">

I am not not sure how this works or if it is still being updated but it would be AMAZING if this could be made to work! Thanks :)

**Comment by u-ashish** [comment]
Closing in favor of https://github.com/scitedotai/scite-zotero-plugin/issues/55

**Comment by u-ashish** [comment]
@fishgirl7 you can now get this from the latest release here: https://github.com/scitedotai/scite-zotero-plugin/releases/tag/v2.0.1

Sorry for the long wait!
