### ISSUE TITLE
Not Seeing Columns in Zotero

### ISSUE THREAD

**Issue by nickles15** [scitedotai/scite-zotero-plugin#58]
Hi. I have installed the plug in, but it doesn't appear how it does in the pictures posted. I cannot see columns of information in zotero, but I can create the scite reports. Any suggestions on how to get the columns?
![image](https://github.com/scitedotai/scite-zotero-plugin/assets/146293868/3d9c2b7d-3958-4f3e-9a12-b7ff7a4bfc28)

**Comment by johnghill** [comment]
Have you tried right-clicking on the column headers? Scite provided columns are: Supporting, Contrasting, Total Distinct, Total Smart.

**Comment by u-ashish** [comment]
Closing since that should work, feel free to re-open if not!
