### ISSUE TITLE
Zotero Plugin not working on my Windows Laptop

### ISSUE THREAD

**Issue by Losinde** [scitedotai/scite-zotero-plugin#59]
I have installed the latest plugin on my Laptop, but when I open Zotero, it does not have the Scite columns. I have uninstalled several times and removed the other Chrome and Word add-ons, but it does not work.

**Comment by sascharo** [comment]
Is this plugin still being maintained?

**Comment by u-ashish** [comment]
@Losinde does this still happen? I wasn't able to reproduce this and it should work now with the latest Zotero 7 compatible release. Can you try and let me know if this needs to be re-opened?
