### ISSUE TITLE
Sorting by the number of citations

### ISSUE THREAD

**Issue by ybeltukov** [scitedotai/scite-zotero-plugin#67]
Thanks for the effort you put into releasing the version for Zotero 7!
I have a small question. I'm trying to sort by the number of citation and the sorting is not correct. Is it a known behavior?

![Screenshot_20240814_145442](https://github.com/user-attachments/assets/e254f4fb-85e3-4ddc-bd84-c43ebd82df9e)

P.S. I do not have Zotero 6 so I can't check the previous behavior.

**Comment by u-ashish** [comment]
Hi @ybeltukov - sorting should work (it worked before and still does for me). I attached a video. What's happening for you? You click and nothing happens? Or the sort order is incorrect? Is there anything in the developer logs?


https://github.com/user-attachments/assets/27319fb6-15c7-4791-bb9e-8ba5581795eb

**Comment by ybeltukov** [comment]
@u-ashish Note that 3927 citations between 3 and 4 citations. The sorting works, but the order is wrong for papers with more than 1000 citations.

**Comment by u-ashish** [comment]
Ohhhh it's because of the commas (I turned them into strings). Will look.

**Comment by u-ashish** [comment]
@ybeltukov this is fixed in https://github.com/scitedotai/scite-zotero-plugin/releases/tag/v2.0.2 -- thanks!
